services:
  postgres:
    image: postgres:15
    container_name: postgres-db-pulseping
    restart: always
    environment:
      POSTGRES_USER: pulseping
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pulseping
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
